language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-tinymt/.travis_build_config.rb build_config.rb
script: 
  - make all test
notifications:
  webhooks:
    - secure: "SxpP8dnEZId+E0VM72QzdXNQXuke2rcFuJxNHAwDbhII8urbVGQlOCXE20JXmMhDFzGACOoBrrEiKrblR+uV12RWcCDFRvNwj1ddumgkp6HEM95t+mw6uuVLxt+uckIY2TgYIWQ6gc1z/twqjWGBKmry3dyuhoC3pQuHsexNOcQ="
